DROP TABLE securities IF EXISTS;
DROP TABLE histories IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 1;

CREATE TABLE securities
(
    id                   INTEGER PRIMARY KEY,
    secid                VARCHAR(255) NOT NULL,
    short_name           VARCHAR(255) NOT NULL,
    reg_number           VARCHAR(255) NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    isin                 VARCHAR(255) NOT NULL,
    is_traded            INTEGER      NOT NULL,
    emitent_id           INTEGER      NOT NULL,
    emitent_title        VARCHAR(255) NOT NULL,
    emitent_inn          VARCHAR(255) NOT NULL,
    emitent_okpo         VARCHAR(255) NOT NULL,
    gos_reg              VARCHAR(255) NOT NULL,
    type                 VARCHAR(255) NOT NULL,
    sec_group            VARCHAR(255) NOT NULL,
    primary_board_id     VARCHAR(255) NOT NULL,
    marketprice_board_id VARCHAR(255) NOT NULL

);
-- CREATE UNIQUE INDEX security_unique_name_secid_idx
--     ON securities (name, secid);

CREATE TABLE histories
(
    id                         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    board_id                   VARCHAR(255) NOT NULL,
    trade_date                 DATE,
    short_name                 VARCHAR(255) NOT NULL,
    secid                      VARCHAR(255) NOT NULL,
    num_trades                 DOUBLE       NOT NULL,
    value                      DOUBLE       NOT NULL,
    open                       DOUBLE       NOT NULL,
    low                        DOUBLE       NOT NULL,
    high                       DOUBLE       NOT NULL,
    legal_close_price          DOUBLE       NOT NULL,
    wa_price                   DOUBLE       NOT NULL,
    close                      DOUBLE       NOT NULL,
    volume                     DOUBLE       NOT NULL,
    market_price2              DOUBLE       NOT NULL,
    market_price3              DOUBLE       NOT NULL,
    admitted_quote             DOUBLE       NOT NULL,
    mp2_val_trd                DOUBLE       NOT NULL,
    market_price3_trades_value DOUBLE       NOT NULL,
    admitted_value             DOUBLE       NOT NULL,
    wa_val                     DOUBLE       NOT NULL,
    security_id                INTEGER      NOT NULL,

    FOREIGN KEY (security_id) REFERENCES securities (id) ON DELETE CASCADE
);
