DROP TABLE histories IF EXISTS;
DROP TABLE securities IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 1;

CREATE TABLE securities
(
    id                   INTEGER PRIMARY KEY,
    secid                VARCHAR(255) NOT NULL,
    short_name           VARCHAR(255),
    reg_number           VARCHAR(255),
    name                 VARCHAR(255),
    isin                 VARCHAR(255),
    is_traded            INTEGER,
    emitent_id           INTEGER,
    emitent_title        VARCHAR(255),
    emitent_inn          VARCHAR(255),
    emitent_okpo         VARCHAR(255),
    gos_reg              VARCHAR(255),
    type                 VARCHAR(255),
    sec_group            VARCHAR(255),
    primary_board_id     VARCHAR(255),
    marketprice_board_id VARCHAR(255)

);


CREATE TABLE histories
(
    id                         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    board_id                   VARCHAR(255),
    trade_date                 DATE,
    short_name                 VARCHAR(255),
    secid                      VARCHAR(255) NOT NULL,
    num_trades                 DOUBLE,
    value                      DOUBLE,
    open                       DOUBLE,
    low                        DOUBLE,
    high                       DOUBLE,
    legal_close_price          DOUBLE,
    wa_price                   DOUBLE,
    close                      DOUBLE,
    volume                     DOUBLE,
    market_price2              DOUBLE,
    market_price3              DOUBLE,
    admitted_quote             DOUBLE,
    mp2_val_trd                DOUBLE,
    market_price3_trades_value DOUBLE,
    admitted_value             DOUBLE,
    wa_val                     DOUBLE,
    security_id                INTEGER      NOT NULL,

    FOREIGN KEY (security_id) REFERENCES securities (id) ON DELETE CASCADE
);
