DROP TABLE securities IF EXISTS;
DROP TABLE histories IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 1;

CREATE TABLE securities
(
    id            INTEGER PRIMARY KEY,
    secid         VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    emitent_title VARCHAR(255) NOT NULL

);
CREATE UNIQUE INDEX security_unique_name_secid_idx
    ON securities (name, secid);

CREATE TABLE histories
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    trade_date  DATE         NOT NULL,
    num_trades  DOUBLE       NOT NULL,
    open        DOUBLE       NOT NULL,
    close       DOUBLE       NOT NULL,
    secid       VARCHAR(255) NOT NULL,
    security_id INTEGER      NOT NULL,
    FOREIGN KEY (security_id) REFERENCES securities (id) ON DELETE CASCADE
);
-- CREATE UNIQUE INDEX unique_secid_tradedate_idx
--   ON histories (secid, num_trades)